<?php

function title_case_menu() {
  $items['title_case'] = array(
    'title' => 'Title Case',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('title_case_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['title_case_success_page'] = array(
    'title' => 'Success',
    'page callback' => 'title_case_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function title_case_form() {
  $form['input_string'] = array(
    '#title' => 'Input String',
    '#type' => 'textfield',
    '#description' => t('Please enter some text to be turned into title case'),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  return $form;
}

function title_case_form_submit($form, &$form_state) {
  $input_string = $form_state['values']['input_string'];

  //Preposition and conjunction array
  $prep_con = array("a","an","and","as","at","but","by",
  "en","for","if","in","of","on","or","the","to", "from");

  //prefixes to check for
  $prefix = array("mc", "o'");

  //Seperates string by space and stores into an array
  $input_array_of_words = explode(" ", strtolower($input_string));

  //Grab first index
  $first_word = ucfirst(array_shift($input_array_of_words));

  //Storage array
  $output_titlecased = array();

  //Caps the first letter of all words
  foreach($input_array_of_words as $word) {
      //Checks to see if the input is a conjuction or prep
      /// if it is then we make sure to not capitalize it.
      if(in_array($word, $prep_con)){
          array_push($output_titlecased, $word);
      //Prefix fix
      }elseif(in_array(substr($word, 0, 2), $prefix)){
          $storage = str_split($word);
          $storage[2] = strtoupper($storage[2]);
          $storage = implode("", $storage);
          array_push($output_titlecased, ucfirst($storage));
      }else{
          array_push($output_titlecased, ucfirst($word));
      }
  }

  //Add first word back to array
  array_unshift($output_titlecased, $first_word);
  $_SESSION['title_case_output'] = implode(" ", $output_titlecased);
  $form_state['redirect'] = 'title_case_success_page';
}

function title_case_success() {
  return "Here is your string in title case: " . $_SESSION['title_case_output'];
}
