<?php

function queen_attack_menu() {
  $items['queen_attack'] = array(
    'title' => 'Queen Attack',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('queen_attack_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['queen_attack_results_page'] = array(
    'title' => 'Results',
    'page callback' => 'queen_attack_results',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function queen_attack_form() {
  $form['queen_column'] = array(
    '#title' => 'Queen Column',
    '#type' => 'select',
    '#options' => array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'),
    '#description' => t('Please input the column of the queen'),
  );
  $form['queen_row'] = array(
    '#title' => 'Queen Row',
    '#type' => 'select',
    '#options' => array(1, 2, 3, 4, 5, 6, 7, 8),
    '#description' => t('Please input the row of the queen'),
  );
  $form['attack_column'] = array(
    '#title' => 'Attacked Column',
    '#type' => 'select',
    '#options' => array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'),
    '#description' => t('Please input the column of the piece to attack'),
  );
  $form['attack_row'] = array(
    '#title' => 'Attacked Row',
    '#type' => 'select',
    '#options' => array(1, 2, 3, 4, 5, 6, 7, 8),
    '#description' => t('Please input the row of the piece to attack'),
  );
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Go',
    );
  return $form;
}

function queen_attack_form_submit($form, &$form_state) {
  $queen_column = $form_state['values']['queen_column'];
  $queen_row = $form_state['values']['queen_row'];
  $attack_column = $form_state['values']['attack_column'];
  $attack_row = $form_state['values']['attack_row'];

  if(($queen_column === $attack_column) || ($queen_row === $attack_row)) {
    $result = true;
  } elseif(abs($queen_column-$attack_column) === abs($queen_row-$attack_row)) {
    $result = true;
  } else {
    $result = false;
  }

  $_SESSION['queen_attack_output'] = $result;
  $form_state['redirect'] = 'queen_attack_results_page';
}

function queen_attack_results() {
  $result_display = $_SESSION['queen_attack_output'];
  if($result_display === TRUE) {
    return '<p>The queen can attack that piece!</p>';
  } else {
    return '<p>The queen cannot attack that piece!</p>';
  }
}
